# ─────────────────────────────────────────────────────────
# Markdown reporter — generate .md report
# ─────────────────────────────────────────────────────────
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..models import AuditResult, ChecklistItem, CoverageReport


def export_markdown(
    path: str,
    task: str,
    desc: str,
    result: AuditResult,
    checklist: list[ChecklistItem],
    coverage: Optional[CoverageReport] = None,
    coverage_threshold: float = 80.0,
) -> None:
    """Generate markdown report — ใช้ list + join เพื่อความเร็ว"""

    title_by_id = {item.id: item.title for item in checklist}
    cat_by_id = {item.id: item.category for item in checklist}

    counts: dict[str, int] = {"done": 0, "missing": 0, "partial": 0, "not_applicable": 0}
    for r in result.results:
        status = r.get("status", "missing")
        if status not in counts:
            status = "missing"
        counts[status] += 1

    total = len(result.results)
    done_pct = (counts["done"] * 100 // total) if total > 0 else 0

    icons = {"done": "✅", "missing": "❌", "partial": "🟡", "not_applicable": "⚪"}

    # ใช้ list แล้ว join ทีหลัง = เร็วกว่า += string
    lines = [
        f"# 🔍 Code Audit Report — {task}",
        "",
    ]
    if desc:
        lines += [f"> {desc}", ""]

    lines += [
        f"**Generated:** `{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}`  ",
        f"**Progress:** `{counts['done']}/{total} steps done ({done_pct}%)`",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
        result.summary,
        "",
        "## 📈 Stats",
        "",
        "| Status | Count |",
        "|--------|-------|",
        f"| ✓ Done | {counts['done']} |",
        f"| ✗ Missing | {counts['missing']} |",
        f"| ◐ Partial | {counts['partial']} |",
        f"| — N/A | {counts['not_applicable']} |",
        "",
        "## ✓ Checklist Results",
        "",
    ]

    for r in result.results:
        status = r.get("status", "missing")
        icon = icons.get(status, "⚪")
        step_id = r.get("stepId") or r.get("id") or ""
        title = title_by_id.get(step_id) or r.get("title") or step_id or "(unnamed)"
        cat = cat_by_id.get(step_id, r.get("category", ""))
        cat_str = f" `{cat.upper()}`" if cat else ""
        lines.append(f"- {icon} **{title}**{cat_str}")
        if r.get("evidence"):
            lines.append(f"  - _{r['evidence']}_")

    # Coverage section
    if coverage is not None:
        lines += ["", "## 📊 Test Coverage", ""]
        if not coverage.ran:
            lines += [f"> ⚠ ไม่สามารถรัน coverage: {coverage.error}", ""]
        else:
            passed = coverage.overall_percent >= coverage_threshold
            mark = "✅" if passed else "❌"
            lines += [
                f"**Overall:** {mark} `{coverage.overall_percent:.1f}%` (threshold: `{coverage_threshold:.0f}%`)",
                "",
                "| Package | Coverage |",
                "|---------|----------|",
            ]
            for p in coverage.packages:
                if not p.has_tests:
                    lines.append(f"| `{p.package}` | _no tests_ |")
                else:
                    pmark = "✅" if p.percent >= coverage_threshold else "🟡" if p.percent >= 50 else "🔴"
                    lines.append(f"| `{p.package}` | {pmark} {p.percent:.1f}% |")
            for fp in coverage.failed_packages:
                lines.append(f"| `{fp}` | ❌ FAIL |")
            lines.append("")

    lines += ["", "## ⚠ Missing Items (not in checklist)", ""]
    if not result.missing_items:
        lines.append("_✓ ไม่มีอะไรขาดเพิ่มเติม_")
    else:
        for m in result.missing_items:
            lines += [
                f"### `{m.get('severity', 'low').upper()}` — {m['title']}",
                "",
                m.get("reason", ""),
                "",
            ]

    lines += ["", "---", "_Generated by taskaudit • Powered by AI_", ""]

    Path(path).write_text("\n".join(lines), encoding="utf-8")
